language: android
jdk: oraclejdk8
dist: trusty
android:
  components:
  - build-tools-28.0.3
  - android-28
script:
- "./gradlew assembleProductionRelease"
deploy:
  provider: releases
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: STZ3GgkRifzhMunZ9WA9vQqSGvP/h/2fWHDDF82vqPR5FjMAqIIMj3K4NKYuTj/ge/gxoHghJYXRBSa/DsWAe5CIKt72s1WnXlPo+8kg8ZnyWajmLBV9Xd5iok5vP67GZG7QeENg5usmWczI4nt+c+8cj41zsMbWoAPbBj7vQak1ySat+MuqR9W0OCGMyhAyX+ey+ot75WYwIuHaOYbKyid8iZAo2P88Tb8lcbFB6YpDhUhe71n/2/NHIDueds0qBRwINzXBhUCgEST4j9mduJPwsw7VdArX4Cl0/lY8up565s/gFgvCoTjz4v1sHm6Jy0m1qWZlf7OLqhxkH0rEcXWncxBmyLTltdGMXILehfcGuFxSXQatL+fhdsw96l0UrWCznl4SE3KxbONQ5exTu38qsHOH85A/UpskZDKwWYTk4icWucriMKo3dua5xNxg923r7Gpjxjyf+RsU6Q7AN7T0fg586jGkYRLkOq88A2suP9lTlDCX/1cUdsJGM5ijXcdYSs0Vi9oJp/H4HxT7unQfboi6vurK4YGqSRLW7DPyCLytelSBRuGbluXqc8pvHaYpFDxEf1y3inuox43X5C+Bo3DGHk9By0aWd+l7+CcKLJpsKGSpghzr/3ExtROiorP+Pro08vE3bZs+UVzF8OdQ2us+D796uGBZw9+KkAY=
  file_glob: true
  file: /home/travis/build/7LPdWcaW/GrowTracker-Android/app/build/outputs/apk/production/release/*
  on:
    repo: 7LPdWcaW/GrowTracker-Android
    tags: true
